security:
 jwt:
  token:
   secret-key: DLatam-SecretKey
   expire-length: 3600000
   
spring:
  main:
    allow-circular-references: true
    
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
server:
  port: 8082